model : lgbm    # {lstm, lstmattn, bert, lgbm}

wandb :
    using: True
    project: DKT
    entity: vail131
    tags: 
        - baseline

##main params
task_name: 5fold_add_global_time_feature_plus_usertime
seed: 42
device: cuda

data_dir: /opt/ml/input/data/train_dataset
asset_dir: asset/
file_name: time_train.csv
model_dir: models/
output_dir: output/
test_file_name: time_test.csv

num_workers: 1

##non-lgbm 모델
max_seq_len: 20
hidden_dim : 128
n_layers : 4
n_heads : 2
drop_out: 0.2

#train
n_epochs: 50
batch_size: 64
lr: 0.0001
clip_grad : 10
patience : 5
log_steps : 50

#중요
optimizer : adam
scheduler: plateau
   

#use only in lgbm
lgbm:
    model_params: {
                    'objective': 'binary', # 이진 분류
                    'boosting_type': 'gbdt',
                    'metric': 'auc', # 평가 지표 설정
                    # 'feature_fraction': 0.8, # 원래 0.8 피처 샘플링 비율
                    # 'bagging_fraction': 0.8, # 원래 0.8 데이터 샘플링 비율
                    # 'bagging_freq': 1,
                    # 'n_estimators': 10000, # 트리 개수
                    'seed': 42,
                    'verbose': -1,
                    'n_jobs': -1,
                    }

    verbose_eval : 100 #ori 100
    num_boost_round : 1000
    early_stopping_rounds : 100

make_sharing_feature : True #extract statistics featrue from train + test(except last rows)
use_test_data : True #use test_data for train
use_kfold : True #n개의 fold를 이용하여 k-fold를 진행한다.
n_fold : 5
split_by_user : True #k-fold를 수행할 dataset을 user 기준으로 split